package userInterface;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.ContextMenuEvent;

public class LoginUIController {
	@FXML
	private Button logIn;
	@FXML
	private Button signUp;
	@FXML
	private Button forgotPassword;

	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void close_application(MouseEvent event) {
		if(ConfirmBox.display("System Exit", "Do you want to close the application?"))
			System.exit(0);
	}
	// Event Listener on Button[#logIn].onMouseClicked
	@FXML
	public void loginClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#signUp].onMouseClicked
	@FXML
	public void signupClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#forgotPassword].onContextMenuRequested
	@FXML
	public void getQuestion(ContextMenuEvent event) {
		// TODO Autogenerated
	}
}
